[package]
name = "ore-cli"
version = "3.5.0"
edition = "2021"
license = "MIT"
description = "ORE quantum secure smart wallet"
homepage = "https://ore.supply"
repository = "https://github.com/regolith-labs/ore-cli"

[[bin]]
name = "ore"
path = "src/main.rs"

[dependencies]
solana-instructions-sysvar = "3.0"
pqcrypto-falcon = "0.3"
pqcrypto-traits = "0.3"
solana-sdk = "2.2"
solana-client = "2.2"
solana-address = { version = "2.6", features = ["decode", "curve25519"] }
spl-token = { version = "7", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "6", features = ["no-entrypoint"] }
clap = { version = "4", features = ["derive"] }
toml = "0.8"
serde = { version = "1", features = ["derive"] }
dirs = "6"
sha2 = "0.10"
bs58 = "0.5"
anyhow = "1"
indicatif = "0.17"
qr2term = "0.3"
solana-instruction = "3.4"
ore-stake-api = "0.2.5"
steel = "4.0.4"
bincode = "1"
